modLoader="kotori_scala"
loaderVersion = "[3.3.0,)"
license = "GPL-3.0-only"

[[mods]]
modId = "@mod_id@"
version = "@mod_version@"
displayName = "@mod_name@"
authors="Pixdane"
description = "Gregicality in a modern fashion."
logoFile = ""

[[dependencies.@mod_id@]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.@mod_id@]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.@mod_id@]]
modId = "gtceu"
mandatory = true
versionRange = "[7.5.3,)"
ordering = "AFTER"
side = "BOTH"
